# Generated by Django 5.2.8 on 2025-11-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.FloatField(blank=True, null=True)),
                ('importance', models.IntegerField(blank=True, null=True)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(default='Smart Balance', max_length=50)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
